[CIVP-22369] - bug fix retry on iterate
civisanalytics/civis-python pull request #413
Opened 2020-10-20 16:05 UTC by byndcivilization

fixed retry bug

2020-10-20 21:19 UTC, mheilman requested changes
Would you mind adding/revising a test so that the previous version would fail?

2020-10-20 21:19 UTC, mheilman commented on CHANGELOG.md
> +- fixes bug whereby calls with iterate=True do not retry
could you please put `(#413)` at the end of this?

2020-10-21 15:54 UTC, byndcivilization commented
@mheilman how does this look?

2020-10-21 15:57 UTC, mheilman commented on civis/tests/test_utils.py
> +    for verb in ['head', 'trace', 'get', 'put', 'options', 'delete', 'post']:
This function is the same as the one above except for the name and this line, right? Could you just put the lowercase verb strings in the list in the other function ([here](https://github.com/civisanalytics/civis-python/pull/413/files#diff-f2df2ec5c411a1d0c536fcfb23aa66d7196fa463abd9d22460617bb37d667db2R307))?  `pytest.mark.parametrize` would be another option, but that seems like overkill.

2020-10-21 17:44 UTC, mheilman approved these changes
LGTM

2020-10-28 17:46 UTC, merged