[CIVP-24658] REF Remove PubNub
civisanalytics/civis-python pull request #425
Opened 2021-10-29 16:54 UTC by jacksonlee-civis

This PR removes all PubNub-related code, as we've stopped using PubNub for quite a while. There's no effect to the users of civis-python, because the code being removed has not been triggered since PubNub usage was dropped from Civis Platform.

2021-10-29 22:43 UTC, skomanduri requested changes
Looks great!  Thank you for tackling this and tracking down so much code.

I still see some references to pubnub/channels in cassettes and in `MANIFEST.in`.  Are you able to remove those lines/files as well?  Since you've removed the test code, I think you should be able to remove all the cassettes that are calling `https://api.civisanalytics.com/channels`.

2021-10-29 22:43 UTC, skomanduri commented on civis/futures.py
>  _LONG_POLLING_INTERVAL = 9.5 * 60
I think these lines should be removed as well.

2021-11-01 12:41 UTC, jacksonlee-civis commented
@skomanduri Thanks for catching more PubNub/Channels remnants! I've just removed those as well and the CI builds have passed. This PR is ready for another review.

2021-11-01 16:52 UTC, skomanduri approved these changes
LGTM

🎉  🎉  🎉

2021-11-01 17:03 UTC, merged